name: Test Workflow

on:
  push:
    paths:
      - 'images.csv'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Echo test
        run: echo "Workflow triggered successfully!"
